"""
AgentState — Strongly-Typed Workflow State for LangGraph Orchestration

This TypedDict is the single source of truth for an entire workflow
execution within the LangGraph graph. Every node reads from and writes
to this state — making all transitions explicit, traceable, and auditable.

Design Principles:
- All fields are JSON-serialisable (supports future Redis checkpointing)
- Mutable collections (lists, dicts) are used; LangGraph handles merging
- `executed_ops` stored as List[str] (not set) for JSON-serializability
- `node_transitions` gives a full audit trail of the graph traversal path
- New fields are additive — existing API contract is unchanged
"""

from typing import Any, Dict, List, Optional
from typing_extensions import TypedDict


# ── Sub-record types ─────────────────────────────────────────────────────────

class ToolCallRecord(TypedDict, total=False):
    """
    Audit record for a single tool call within a workflow execution.

    Replaces ToolCallInfo in the internal graph state.
    Converted to ToolCallInfo (Pydantic) before returning via API.
    """
    tool: str               # Tool name: "oms" | "crm" | "kb" | "payments"
    operation: str          # Specific operation performed
    params: Dict[str, Any]  # Parameters passed to the tool
    result: str             # "success" | "error" | "blocked" | "skipped"
    data: Optional[Dict[str, Any]]  # Structured result data
    latency_ms: int         # Per-tool execution latency in milliseconds
    retry_count: int        # Number of retries attempted
    timestamp: str          # ISO-8601 UTC timestamp


class WorkflowStep(TypedDict, total=False):
    """
    A single step in the deterministic execution plan.

    Generated by workflow_planner_node; consumed by deterministic_executor_node.
    The LLM never generates these directly — they are produced deterministically
    from the extracted entities and intent.
    """
    step: int               # 1-based step index
    tool: str               # Target tool name
    operation: str          # Target operation
    params: Dict[str, Any]  # Resolved parameters
    depends_on: List[int]   # Step indices that must succeed before this step runs


# ── Primary AgentState TypedDict ─────────────────────────────────────────────

class AgentState(TypedDict, total=False):
    """
    Complete workflow state for a single customer interaction.

    Lifecycle:
      1. Initialized by orchestrator.py (thin adapter) before graph.ainvoke()
      2. Mutated by graph nodes via returned partial dicts
      3. Finalized by trace_finalizer_node
      4. Converted to QueryResponse by orchestrator.py after graph completes

    Sections:
      - Identity: session/trace/customer identifiers
      - Input: raw and sanitized user message
      - Intent Understanding: regex + LLM-extracted intents and entities
      - Governance: policy violations and escalation flags
      - Execution Plan: ordered list of WorkflowSteps
      - Results: per-tool outcomes
      - Idempotency: deduplication key tracker
      - Observability: per-node latency, traversal path, retry counts
      - Output: final response and completion flags
    """

    # ── Identity ─────────────────────────────────────────────────────────────
    session_id: str         # Client-provided session identifier
    trace_id: str           # UUID generated per-request for full audit trail
    customer_id: str        # Customer identifier for CRM operations
    channel: str            # "chat" | "email" | "voice" (future channels)

    # ── Input ────────────────────────────────────────────────────────────────
    user_message: str       # Original message from the customer
    sanitized_message: str  # After SQL/XSS injection stripping (done in main.py)

    # ── Intent Understanding ─────────────────────────────────────────────────
    regex_intent: str
    # Fast-path result from regex_router_node.
    # Values: "TRACKING" | "COMPOUND" | "ESCALATION" | "POLICY" | "GENERAL"

    extracted_intents: List[str]
    # LLM-extracted intents (may be multiple for mixed-intent queries).
    # Set by structured_extraction_node. Falls back to [regex_intent] on failure.

    detected_entities: Dict[str, Any]
    # Entities extracted from the query: order_id, amount, item_index, new_address.

    order_ids: List[str]
    # All order IDs referenced in the query (supports multi-order queries).

    refund_amount: Optional[float]
    # Extracted refund amount in INR. None if no refund is requested.

    item_indices: List[int]
    # Line item indices referenced (1-based, per OMS convention).

    new_address: Optional[str]
    # New shipping address if an address update was requested.

    conditions: List[str]
    # Conditional clauses extracted from the query.
    # E.g. ["only if not shipped", "only if refund goes to HDFC card"]
    # These are logged for observability but do not affect deterministic execution
    # in the MVP. Extension point for conditional workflow branching.

    actions: List[str]
    # Requested action verbs: ["cancel_item", "initiate_refund", "update_address"]

    # ── Governance ───────────────────────────────────────────────────────────
    policy_violations: List[str]
    # Human-readable descriptions of any policy violations detected.
    # Populated by policy_validation_node (pre-flight) and executor (mid-flight).

    escalation_required: bool
    # True if any policy violation or tool error requires human escalation.
    # Set deterministically — NEVER by LLM reasoning.

    escalation_reason: str
    # Human-readable reason for escalation (included in CRM case summary).

    # ── Execution Plan ───────────────────────────────────────────────────────
    workflow_plan: List[WorkflowStep]
    # Ordered list of tool operations to execute.
    # Generated deterministically by workflow_planner_node.
    # The LLM NEVER generates or modifies this plan directly.

    current_step: int
    # Index into workflow_plan of the currently executing step.

    # ── Results ──────────────────────────────────────────────────────────────
    tool_results: List[ToolCallRecord]
    # Ordered list of all tool call outcomes (success, error, blocked, skipped).
    # This is the primary audit record of tool execution.

    completed_steps: List[int]
    # Step numbers that completed successfully.

    failed_steps: List[int]
    # Step numbers that failed (tool error, policy block, dependency failure).

    skipped_steps: List[int]
    # Step numbers skipped due to idempotency or dependency failure.

    # ── Idempotency ──────────────────────────────────────────────────────────
    executed_ops: List[str]
    # Serialised idempotency keys for operations already executed.
    # Format: "tool:operation:order_id:item_index"
    # Stored as List (not set) for JSON-serializability with future checkpointing.

    # ── Observability ────────────────────────────────────────────────────────
    node_latencies: Dict[str, int]
    # Maps node_name → execution latency in milliseconds.
    # Populated incrementally as each node completes.

    node_transitions: List[str]
    # Ordered list of graph nodes visited during this workflow execution.
    # Provides a complete traversal audit trail.

    retry_counts: Dict[str, int]
    # Maps tool_name → number of retries attempted.

    start_time_ns: int
    # Epoch nanoseconds at workflow start (for precise latency measurement).

    # ── Output ───────────────────────────────────────────────────────────────
    final_response: str
    # The human-readable response text to return to the customer.
    # Set by response_generator_node.

    error_message: str
    # Set if the workflow encountered an unrecoverable error.

    workflow_complete: bool
    # True when the workflow has reached a terminal state.
